[project]
name = "market-surprise-reaction"
authors = [{name = "Harsh Vardhan Gupta", email = "hvgupta@outlook.in"}]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "aiohttp",
    "fastapi[standard]",
    "lxml>=6.1.0",
    "matplotlib>=3.10.0",
    "mypy>=1.20.2",
    "pandas>=3.0.2",
    "pydantic>=2.13.3",
    "python-dotenv",
    "supabase>=2.30.0",
    "uv",
    "yfinance>=1.3.0",
]

[project.urls]
GitHub = "https://github.com/hvgupta/Stock-Surprise-and-Reaction"

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"]

[tool.scripts]
tool-backend = "fastapi dev backend/app.py"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
